name: build

on:
  push:
    branches: 
      - master

    paths-ignore:
      - '**.md'
      - 'LICENSE'

  pull_request:
    branches:
      - '**'


jobs:
  build_stable:
    name: "build (stable)"
    runs-on: ubuntu-latest
    container: rust:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: cargo build -v

      - name: Test
        run: cargo test -v
      
      - name: Examples
        run: |
          cargo run --example background
          cargo run --example foreground
          cargo run --example foreground_with_background
          cargo run --example reset
          cargo run --example styles

  build_nightly:
    name: "build (nightly)"
    runs-on: ubuntu-latest
    container: rustlang/rust:nightly

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: cargo build -v

      - name: Test
        run: cargo test -v
        
      - name: Examples
        run: |
          cargo run --example background
          cargo run --example foreground
          cargo run --example foreground_with_background
          cargo run --example reset
          cargo run --example styles

    continue-on-error: true
