name: build

on:
  push:
    branches: 
      - master

    paths-ignore:
      - '**.md'
      - 'LICENSE'

  pull_request:
    branches:
      - '**'


jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    container: rust:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: cargo build -v

      - name: Test
        run: cargo test -v
